In [1]:
import numpy as np 
import pandas as pd

In [2]:
dataset = pd.read_csv("daily_csv.csv")

In [3]:
dataset.head()

Date  Price
0  1997-01-07   3.82
1  1997-01-08   3.80
2  1997-01-09   3.61
3  1997-01-10   3.92
4  1997-01-13   4.00

In [4]:
dataset['Year'] = pd.DatetimeIndex(dataset['Date']).year
dataset['Month'] = pd.DatetimeIndex(dataset['Date']).month
dataset['Day'] = pd.DatetimeIndex(dataset['Date']).day

In [5]:
dataset.drop('Date', axis=1, inplace=True )

In [6]:
dataset.isnull().any()

Price     True
Year     False
Month    False
Day      False
dtype: bool

In [7]:
dataset['Price'].fillna(dataset['Price'].mean(), inplace= True)

In [8]:
x = dataset.iloc[:,1:4].values
y = dataset.iloc[:,0:1].values

In [9]:
y

array([[3.82],
       [3.8 ],
       [3.61],
       ...,
       [2.15],
       [2.18],
       [2.19]])

In [10]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=2)

In [11]:
from sklearn.linear_model import LinearRegression

In [12]:
lr = LinearRegression()

In [13]:
lr.fit(X_train, y_train)

LinearRegression()

In [14]:
y_pred = lr.predict(X_test)
y_pred

array([[4.51472486],
       [4.59457551],
       [4.75721005],
       ...,
       [3.88764252],
       [4.84084556],
       [4.43592319]])

In [15]:
from sklearn.metrics import r2_score
lr_accuracy = r2_score(y_test, y_pred)
lr_accuracy

0.022503776960346777

# Decision Tree Algorithm

In [16]:
from sklearn.tree import DecisionTreeRegressor

In [17]:
dtr = DecisionTreeRegressor()
dtr.fit(X_train, y_train)

DecisionTreeRegressor()

In [18]:
y_pred2 = dtr.predict(X_test)
y_pred2

array([6.09, 1.97, 2.42, ..., 4.58, 2.21, 5.79])

In [19]:
from sklearn.metrics import r2_score
dtr_accuracy = r2_score(y_test, y_pred2)
dtr_accuracy

0.987363764592228

In [20]:
import pickle
pickle.dump(dtr, open('gas.pkl','wb'))

In [21]:
dataset.head()

Price  Year  Month  Day
0   3.82  1997      1    7
1   3.80  1997      1    8
2   3.61  1997      1    9
3   3.92  1997      1   10
4   4.00  1997      1   13

In [22]:
dtr.predict(pd.DataFrame(columns=['Year','Month','Day'],data=np.array([2000, 5, 5]).reshape(1,3)))

c:\Users\Rutuja\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\base.py:486: UserWarning: X has feature names, but DecisionTreeRegressor was fitted without feature names
  warnings.warn(


array([3.09])